name: Publish to VSCode Marketplace

on:
  push:
    tags:
      - 'v*'
      - '!v*-dev'  # Exclude -dev tags

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'zw3rk/sourcemap-tools'  # Only run on public repo
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build extension
      run: npm run compile

    - name: Package extension
      run: npm run package

    - name: Publish to VSCode Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: npx vsce publish -p $VSCE_PAT

    - name: Upload VSIX as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-package
        path: '*.vsix'

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: '*.vsix'
        body: |
          VSCode extension has been published to the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=zw3rk.source-map-visualizer).
          
          See [CHANGELOG.md](https://github.com/zw3rk/sourcemap-tools/blob/master/CHANGELOG.md) for details.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}